appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
shippable:
  projectId: 5c32d1a54e246e0700cedd92
  secure: {BINSTAR_TOKEN: bkTdATvev7sVFsP62xFV2ck215nXEtH7eWXdhzRRtbzeKquSkNhTGTCoa5FcLDvAVe36w+Sv59/3/oWNyMood8pIWjHLMC5CqqLdc4NRmyyaCKWys4CLhTTurIBPFSWUilxZW1KCKv/WHOe+zQDi2o9R9lf5/MizuwThHSQOIcqeTIn4wtPzbne5MeKSW+mRCsb+l4E/Q1oY2w/mTJ+izDWkxefstZ2t8RqOxH6H20wwNOOj/1WdeztdCOtCAl99r8Aj58odGyfUMAEyw89c5HglAEPurBQs21DZbHp10NmgSLyIbukplulRUm+cQ37loT/hFfTjPUCqLEC3lu6SPw==}
travis:
  secure: {BINSTAR_TOKEN: WNzvK2w1Kk81DjVM4DYCYl9d2hodfjqeX7JTXDjCmSf99AnIm00pew8qDabm+Wwf13YcR38UvNZCaUhCLKBYMQR8L7xZm0ZE8/8bWCGdg3VLeneN7OLfWfII+FKnlsUYnclsl6VHf9wInFeOTv6yaRYSzPbS724lhThnsXbCMtKUWCqtJzaa/YzOP6FIIEMjBTf7m/UG/y/7DLGAsHFYmGeanclvBqViOI9hC6nnejnSLy6LqLt8d1CYElvb1GsHuIcWn/r83Fl9R1NekaCnscS4e69YEahTACd/ATZk7UuaPJigrdgtzuKQ3Tf91CJwRwpaZtOeoL8k9NvDPs+GA6r5PeJau4D8pN/UtnWQ5BHrpxu6XoCHmQcsNjiXXMmOule27S7MhCYnItA1ISvZXVZfbMfQI/T2hvRvuVrMdwtqOckPBkeJkromRtjb8Qv5SIdQW+gkOEEuzc61IJips110mMKjvsng/kOqQ0311VaxGFwCk0335/N/SJ1S2dIUpInK1mA2Hs7Q3x1KotNXkuEyaa/Q8LFubL2jVtFEmEDjYz+VFEUQY+/E/pTqisFi3+Pv8/aY+x+pbzUknJ3S1aRESFlvViR+UXr1Xfn8tIKyQEwUAyLWpWjXcYhl6ylI7w4a4dzFCJUz8o3wvPXSg6vUXltNJVWpLvwn4i1oYtY=}
